"""
Django settings for posvana_api project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-==m#-ekn!_4^g#=xa!+_u608$w*1uhg*osg)tp+1i)8)zoj!ka'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']  # Hanya untuk sementara saat debug!

# Application definition

INSTALLED_APPS = [
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'posvana_api',  # pastikan app ini terdaftar
    'user_auth',     # jika ada app user_auth terpisah
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',  # Dihapus karena tidak digunakan
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'posvana_api.middleware.auth_middleware.JWTAuthenticationMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'posvana_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'posvana_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'angkringan_pos',  # Nama database
    #     'USER': 'postgres',        # Default user PostgreSQL (kalau belum diubah)
    #     'PASSWORD': 'Faturzzz01',  # Password PostgreSQL kamu
    #     'HOST': 'localhost',       # Karena kamu pakai PostgreSQL lokal
    #     'PORT': '5432',            # Default port PostgreSQL
    # },
    'default': dj_database_url.config(default='postgresql://postgres:zMgJOAZHGBMSXLZwjzfyrhHxXqSmjVcp@shuttle.proxy.rlwy.net:53892/railway')

}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Hapus validasi password yang berhubungan dengan auth
AUTH_PASSWORD_VALIDATORS = [
    # Menghapus atau menonaktifkan pengaturan validasi password
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JWT_SECRET = '9@zG#23wsA5$xJqVtYqP2g7^6RpL!!d7tL3fT9o6kDg5YsXK5nF9Dd2sK9Qz0M'
JWT_ALGORITHM = 'HS256'
JWT_EXP_DELTA_SECONDS = 3600  # Token berlaku 1 jam
CORS_ALLOW_ALL_ORIGINS = False  # Untuk development saja!

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Replace with your frontend URL
    "https://your-frontend.com",  # Add your production frontend URL here
    'https://posvanapi-production.up.railway.app',  # ✅ Tambahkan https://
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  # atau 465 kalau mau pakai SSL
EMAIL_USE_TLS = True  # atau False kalau pakai SSL
EMAIL_USE_SSL = False  # True kalau pakai port 465
EMAIL_HOST_USER = 'angkringanomahmu@gmail.com'
EMAIL_HOST_PASSWORD = 'rbpcpktzmjkroxqq'  # Ini adalah App Password dari Google


